apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.name  }}
  namespace: {{ .Values.mysql.namespace  }}
  labels:
    release: "{{ .Release.Name }}"
type: Opaque
data:
  db_secret_key: {{ .Values.mysql.dbpass  }}
  db_secret_user: {{ .Values.mysql.dbuser  }}
