apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Values.webapp.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: {{ .Values.webapp.service.targetport }}
      protocol: TCP
      name: webapp
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
