creation_rules:
    # encrypted using helm-secrets-example-projectx <helm-secrets-projectx@example.com> and helm-secrets-example-projecty <helm-secrets-projecty@example.com>
    - pgp: "55DB347939EDB0B269500B1D9A8F1F237CEC10EC"
